// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sea.proto

#include "sea.pb.h"
#include "sea.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace sea {

static const char* SeaService_method_names[] = {
  "/sea.SeaService/SeaMethod",
};

std::unique_ptr< SeaService::Stub> SeaService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SeaService::Stub> stub(new SeaService::Stub(channel, options));
  return stub;
}

SeaService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SeaMethod_(SeaService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SeaService::Stub::SeaMethod(::grpc::ClientContext* context, const ::sea::SeaRequest& request, ::sea::SeaResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sea::SeaRequest, ::sea::SeaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SeaMethod_, context, request, response);
}

void SeaService::Stub::async::SeaMethod(::grpc::ClientContext* context, const ::sea::SeaRequest* request, ::sea::SeaResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sea::SeaRequest, ::sea::SeaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SeaMethod_, context, request, response, std::move(f));
}

void SeaService::Stub::async::SeaMethod(::grpc::ClientContext* context, const ::sea::SeaRequest* request, ::sea::SeaResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SeaMethod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sea::SeaResponse>* SeaService::Stub::PrepareAsyncSeaMethodRaw(::grpc::ClientContext* context, const ::sea::SeaRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sea::SeaResponse, ::sea::SeaRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SeaMethod_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sea::SeaResponse>* SeaService::Stub::AsyncSeaMethodRaw(::grpc::ClientContext* context, const ::sea::SeaRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSeaMethodRaw(context, request, cq);
  result->StartCall();
  return result;
}

SeaService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SeaService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SeaService::Service, ::sea::SeaRequest, ::sea::SeaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SeaService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sea::SeaRequest* req,
             ::sea::SeaResponse* resp) {
               return service->SeaMethod(ctx, req, resp);
             }, this)));
}

SeaService::Service::~Service() {
}

::grpc::Status SeaService::Service::SeaMethod(::grpc::ServerContext* context, const ::sea::SeaRequest* request, ::sea::SeaResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sea

